### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by pcarbo** [btupper/catecolors#1]
@btupper I believe this line in `misc.R`:

```r
if (missing(index)) index <- seq_len(nrows(LUT))
```

should be

```r
if (missing(index)) index <- seq_len(nrow(LUT))
```

Thanks for providing this nice package.

**Comment by btupper** [comment]
Thank you!  I haven't used this package (we have someone who is colorblind in our group and these don't work for him), but it was fun to document them for R.
